apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
  namespace: {{ .Values.ns }}
spec:
  ports:
  - port: {{ .Values.port.exposedPort }}
    protocol: TCP
    targetPort: {{ .Values.port.targetPort }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
