apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxuat
  namespace: argocd
spec:
  destination:
    namespace: nginxuat
    server: 'https://kubernetes.default.svc'
  source:
    path: firstci
    repoURL: 'https://github.com/tferfce/argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_uat.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      prune: true
      selfHeal: true