apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxuat
spec:
  destination:
    name: ''
    namespace: uat
    server: 'https://kubernetes.default.svc'
  source:
    path: firstci
    repoURL: 'https://github.com/tferfce/argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_uat.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true