apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxdev
  namespace: dev
spec:
  destination:
    name: ''
    namespace: nginxdev
    server: 'https://kubernetes.default.svc'
  source:
    path: firstci
    repoURL: 'https://github.com/tferfce/argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_dev.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true